name: flutter_app_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^0.13.6
  shared_preferences: ^2.0.15
  image_picker: ^0.8.4+6
  easy_localization: ^3.0.1
  razorpay_flutter: ^1.3.7
  fluttertoast: ^8.2.2
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/images/logo.png
    - assets/images/dosa.jpg
    - assets/images/idli.jpg
    - assets/images/puri.jpg
    - assets/images/vada.jpg
    - assets/images/breakfast.jpg
    - assets/images/lunch.jpg
    - assets/images/snacks.jpg
    - assets/images/springroll.jpg
    - assets/images/pasta.jpg
    - assets/images/noodles.jpg
    - assets/images/paneertikka.jpg
    - assets/images/friedrice.jpg
    - assets/images/meals.jpg
    - assets/images/biryani.jpg
    - assets/images/chapathi.jpg

  



